name: Trigger Update Website Build

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Update Website Build
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.REPO_Quartabill_Site_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/entttom/Quartabill-site/dispatches \
            -d '{"event_type":"build-trigger"}'
